version: '3.8'
services:
  airflow-webserver:
    hostname: airflow
    container_name: airflow
    image: andrejunior/airflow-spark:latest
    restart: always
    networks:
        - airflow
    depends_on:
      - postgres
      - minio
      - spark-master
      - spark-worker
    environment:   
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - LOAD_EX=n
      - EXECUTOR=Local    
    volumes:
      - airflow-data:/usr/local/airflow/data
      # - ./src/dags:/usr/local/airflow/dags
      # - ./src/spark/applications:/usr/local/spark/applications            
      # - ./src/spark/assets:/usr/local/spark/assets     
    ports:
        - "8085:8080"
    command: webserver
    healthcheck:
        test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
        interval: 30s
        timeout: 30s
        retries: 3

  postgres:
    hostname: postgres
    container_name: postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: 'dev'
      POSTGRES_PASSWORD: 'dev'
      POSTGRES_DB: 'loan_approval'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure
    healthcheck:
        test: ["CMD", "pg_isready"]
        interval: 60s
        timeout: 20s
        retries: 3
    
  minio:
    hostname: bucket 
    container_name: bucket
    image: 'bitnami/minio:latest'
    environment:
        MINIO_ROOT_USER: airflow
        MINIO_ROOT_PASSWORD: airflow
    ports:
        - '9000:9000'
        - '9001:9001'
    volumes:
        - minio_data:/data
    networks:
        - airflow
    healthcheck:
        test: ["CMD", "curl", "-f", "http://bucket:9000/minio/health/live"]
        interval: 60s
        timeout: 20s
        retries: 3